import Logo from "@/components/logo";
import type { Metadata } from "next";
import { Tektur, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import GithubIcon from "@/components/icons/github";
import XIcon from "@/components/icons/x";
import RibbonIcon from "@/components/icons/ribbon";

const tektur = Tektur({
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-tektur",
});
const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-plus-jakarta-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${tektur.variable} ${plusJakartaSans.variable} h-full`}
    >
      <body className="flex min-h-full flex-col bg-gray-300 text-gray-500 antialiased">
        <header className="px-4 py-2 md:py-5">
          <div className="mx-auto flex max-w-screen-2xl justify-between">
            <Link href="/">
              <Logo />
            </Link>

            <Button
              asChild
              className="size-8 font-title font-bold md:size-auto"
            >
              <Link href="/top-models">
                <RibbonIcon />
                <span className="hidden md:inline">Leaderboard</span>
              </Link>
            </Button>
          </div>
        </header>

        <main className="grow px-4 py-8">{children}</main>

        <footer className="mt-16 px-2 py-2 md:px-4 md:py-8">
          <div className="mx-auto flex w-full max-w-screen-2xl items-center justify-between">
            <p className="text-xs md:text-sm">Powered by Together.ai</p>
            <div className="inline-flex items-center gap-2">
              <Button
                variant="ghost"
                className="rounded-md border border-gray-500 px-3 text-xs"
                asChild
              >
                <Link href="#">
                  <GithubIcon />
                  GitHub
                </Link>
              </Button>
              <Button
                variant="ghost"
                className="rounded-md border border-gray-500 px-3 text-xs"
                asChild
              >
                <Link href="#">
                  <XIcon />
                  Twitter
                </Link>
              </Button>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
